
services:
  db:
    image: postgres:15-alpine
    container_name: helpdeskpro_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: helpdeskpro
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:9-alpine
    container_name: helpdeskpro_flyway
    depends_on:
      - db
    command: -url=jdbc:postgresql://db:5432/helpdeskpro -user=admin -password=password -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql

volumes:
  pgdata:
