spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/helpdeskpro
    username: admin
    password: password
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/helpdeskpro
    user: admin
    password: password

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  metrics:
    tags:
      application: HelpDeskPro
